from openfold import format_input

def test_format_input():
    assert format_input("MaAHKGAEHHHKAAEHHEQAAKHHHAAAEHHeKGEHEQAAHHADTAYAHHKHAeeHAAQAAKHDAEHHAPKPH") == "MAAHKGAEHHHKAAEHHEQAAKHHHAAAEHHEKGEHEQAAHHADTAYAHHKHAEEHAAQAAKHDAEHHAPKPH"